version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    env_file: ./.env
    ports:
      - "5432:5432"
